name: deploy to data:8400
on:
  push:
    branches: [ oncology-screening-branch ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD_HOST }}
        username: ${{ secrets.CICD_USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: |
          cd /apps/kenyaemr
          sudo rm -rf openmrs-module-kenyaemr
          sudo mkdir openmrs-module-kenyaemr
          sudo chown -R cicd:cicd openmrs-module-kenyaemr
          git config --global --add safe.directory /apps/kenyaemr/openmrs-module-kenyaemr
          cd /apps/kenyaemr/openmrs-module-kenyaemr
          git clone -b oncology-screening-branch https://github.com/palladiumkenya/openmrs-module-kenyaemr.git .
          sudo chown -R cicd:cicd /apps/kenyaemr/openmrs-module-kenyaemr
          git status
          sudo mvn license:format
          sudo mvn clean install -DskipTests
          ${{ secrets.DOCKER8400 }}
          echo "Done!"        
